services:
  - type: web
    name: modestwear
    env: python
    buildCommand: "cd modestwear && pip install -r requirements.txt && pip install -r requirements-prod.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd modestwear && gunicorn core.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings_prod
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: modestwear-db
          property: connectionString

databases:
  - name: modestwear-db
    databaseName: modestwear
    user: modestwear